In [1]:
!pip install pandas numpy matplotlib seaborn scikit-learn

  Using cached pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
  Using cached numpy-2.5.2-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
  Using cached matplotlib-3.11.1-cp313-cp313-win_amd64.whl.metadata (80 kB)
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
  Using cached scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
  Using cached tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached contourpy-1.3.3-cp313-cp313-win_amd64.whl.metadata (5.5 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached pillow-12.3.0-cp313-cp313-win_amd64.whl.metadata (9.3 kB)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
  Using cached narwhals-2.25.0-py3-none-any.whl.metadata (15 kB)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
Using cached numpy-2.5.2-cp313-cp313-win_amd64.whl (12.5 MB)
Using cached matplotlib-3.11.1-cp313-c

In [2]:
import pandas as pd

df_booking  = pd.read_csv(r'C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\Projects\Rapido\src\DataCSVFiles\bookings.csv')

df_booking.head()

df_booking.drop(['booking_id', 'actual_ride_time_min', 'drop_location'], axis=1, inplace=True)

df_booking.head()



from sklearn.preprocessing import OrdinalEncoder


encoder = OrdinalEncoder(categories=[[ "Low", #Ordinal
        "Medium",
        "High"]])

df_booking['traffic_level'] = encoder.fit_transform(df_booking[['traffic_level']])

encoder = OrdinalEncoder(categories=[[ "Clear", #Ordinal
        "Rain",
        "Heavy Rain"]])

df_booking['weather_condition'] = encoder.fit_transform(df_booking[['weather_condition']])

df_booking['booking_date'] = pd.to_datetime(df_booking['booking_date'])
df_booking['booking_time'] = pd.to_datetime(df_booking['booking_time'])

df_booking['Fare_per_KM'] = df_booking['booking_value'] / df_booking['ride_distance_km']
df_booking['Fare_per_Min'] = df_booking['booking_value'] / df_booking['estimated_ride_time_min']

df_booking['Long_Distance_Flag'] = df_booking['ride_distance_km'] > 20


C:\Users\KITTU-PALKIN\AppData\Local\Temp\ipykernel_23416\2079420826.py:29: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_booking['booking_time'] = pd.to_datetime(df_booking['booking_time'])


In [3]:
import pandas as pd

df_cust  = pd.read_csv(r'C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\Projects\Rapido\src\DataCSVFiles\customers.csv')

df_cust.head()

df_cust.drop(['customer_city','customer_age'], axis=1, inplace=True)

df_cust.head()

df_cust = pd.get_dummies(df_cust,columns=['preferred_vehicle_type','customer_gender'],dtype='int')

In [4]:
import pandas as pd

df_driver  = pd.read_csv(r'C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\Projects\Rapido\src\DataCSVFiles\drivers.csv')

df_driver.head()

df_driver.drop(['driver_city','driver_age'], axis=1, inplace=True)

df_driver.head()

df_driver = pd.get_dummies(df_driver,columns=['vehicle_type'],dtype='int')

df_driver.isna().sum()
df_driver.duplicated().sum() 
df_driver.head()



,driver_id,driver_experience_years,total_assigned_rides,accepted_rides,incomplete_rides,delay_count,acceptance_rate,delay_rate,avg_driver_rating,avg_pickup_delay_min,driver_delay_flag,vehicle_type_Auto,vehicle_type_Bike,vehicle_type_Cab
0,D_000001,1,25,16,0,0,0.64,0.00,4.1,2.0,0,1,0,0
1,D_000002,2,14,11,3,2,0.79,0.14,4.8,6.1,1,0,0,1
2,D_000003,12,19,14,3,2,0.74,0.11,4.1,2.6,1,1,0,0
3,D_000004,3,18,13,2,2,0.72,0.11,4.2,2.6,1,1,0,0
4,D_000005,7,18,16,1,1,0.89,0.06,4.8,4.9,0,0,1,0


In [5]:
import pandas as pd

df_loc  = pd.read_csv(r'C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\Projects\Rapido\src\DataCSVFiles\location_demand.csv')

df_loc.head()

#df_driver.drop(['driver_city','driver_age'], axis=1, inplace=True)

#df_driver.head()

#df_driver = pd.get_dummies(df_driver,columns=['vehicle_type'],dtype='int')

#df_driver.isna().sum()
#df_driver.duplicated().sum() 
#df_driver.head()


df_booking = df_booking.merge(
    df_loc,
    on=['city', 'pickup_location', 'hour_of_day', 'vehicle_type'],
    how='left',
    validate='many_to_one'
)

df_booking = pd.get_dummies(df_booking,columns=['day_of_week', 'city','vehicle_type','demand_level'],dtype='int')

In [60]:
df_booking.shape

(100000, 41)

In [6]:
import pandas as pd

df_time  = pd.read_csv(r'C:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\Projects\Rapido\src\DataCSVFiles\time_features.csv')

df_time.head()

#df_driver.drop(['driver_city','driver_age'], axis=1, inplace=True)

#df_driver.head()

#df_driver = pd.get_dummies(df_driver,columns=['vehicle_type'],dtype='int')

#df_driver.isna().sum()
#df_driver.duplicated().sum() 
#df_driver.head()

unique_time = df_time[['hour_of_day', 'peak_time_flag']].drop_duplicates(subset=['hour_of_day'])
unique_time.shape



(24, 2)

In [7]:
df_booking = pd.merge(df_booking, unique_time[['hour_of_day','peak_time_flag']], on='hour_of_day', how='left')


df_booking.head()
df_booking.shape

(100000, 42)

In [8]:
df_booking = pd.merge(df_booking, df_driver, on='driver_id', how='left')


df_booking.head()
df_booking.shape

(100000, 55)

In [9]:
df_booking = pd.merge(df_booking, df_cust, on='customer_id', how='left')


df_booking.head()
df_booking.shape

(100000, 69)

In [10]:
# Tell pandas to display every single column
pd.set_option('display.max_columns', None)

df_booking['Long_Distance_Flag'] = df_booking['Long_Distance_Flag'].astype(int)
df_booking['booking_year'] = df_booking['booking_date'].dt.year
df_booking['booking_month'] = df_booking['booking_date'].dt.month
df_booking['booking_day'] = df_booking['booking_date'].dt.day

df_booking.drop(['customer_id', 'driver_id','incomplete_ride_reason','booking_date','booking_time','pickup_location'], axis=1, inplace=True)

df_booking.head()


,is_weekend,hour_of_day,ride_distance_km,estimated_ride_time_min,traffic_level,weather_condition,base_fare,surge_multiplier,booking_value,booking_status,Fare_per_KM,Fare_per_Min,Long_Distance_Flag,total_requests,completed_rides_x,cancelled_rides_x,avg_wait_time_min,avg_surge_multiplier,day_of_week_Friday,day_of_week_Monday,day_of_week_Saturday,day_of_week_Sunday,day_of_week_Thursday,day_of_week_Tuesday,day_of_week_Wednesday,city_Bangalore,city_Chennai,city_Delhi,city_Hyderabad,city_Mumbai,vehicle_type_Auto_x,vehicle_type_Bike_x,vehicle_type_Cab_x,demand_level_Low,demand_level_Medium,peak_time_flag,driver_experience_years,total_assigned_rides,accepted_rides,incomplete_rides_x,delay_count,acceptance_rate,delay_rate,avg_driver_rating,avg_pickup_delay_min,driver_delay_flag,vehicle_type_Auto_y,vehicle_type_Bike_y,vehicle_type_Cab_y,customer_signup_days_ago,total_bookings,completed_rides_y,cancelled_rides_y,incomplete_rides_y,cancellation_rate,avg_customer_rating,customer_cancel_flag,preferred_vehicle_type_Auto,preferred_vehicle_type_Bike,preferred_vehicle_type_Cab,customer_gender_Female,customer_gender_Male,customer_gender_Non-Binary,booking_year,booking_month,booking_day
0,0,0,7.01,46.30,2.0,2.0,76.12,2.0,148.22,Cancelled,21.144080,3.201296,0,4,3,1,51.002500,1.525000,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,0,10,18,16,2,1,0.89,0.06,4.9,2.9,0,0,0,1,548,16,13,3,0,0.187500,4.3,0,0,1,0,0,1,0,2025,12,11
1,0,6,9.67,43.54,1.0,2.0,254.15,1.8,465.85,Completed,48.174767,10.699357,0,4,4,0,47.202500,1.575000,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,5,18,14,2,1,0.78,0.06,4.6,3.9,0,1,0,0,848,10,10,0,0,0.000000,4.7,0,0,0,1,1,0,0,2025,7,7
2,1,8,16.18,48.55,0.0,2.0,234.20,1.9,457.03,Cancelled,28.246601,9.413594,0,7,4,3,68.342857,1.685714,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,1,14,27,22,4,4,0.81,0.15,4.4,5.2,1,0,0,1,161,6,2,3,1,0.500000,3.7,1,0,0,1,1,0,0,2025,8,23
3,1,10,1.02,4.61,1.0,1.0,28.20,1.8,51.03,Completed,50.029412,11.069414,0,3,2,1,27.963333,1.566667,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,1,0,1,14,25,17,3,2,0.68,0.08,4.2,3.2,0,0,0,1,322,11,8,2,1,0.181818,3.7,0,0,0,1,1,0,0,2025,4,12
4,1,0,12.35,55.56,1.0,0.0,118.77,1.2,144.73,Completed,11.719028,2.604932,0,8,7,1,91.583750,1.400000,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,4,15,12,1,1,0.80,0.07,4.5,4.0,0,1,0,0,855,13,11,0,2,0.000000,4.4,0,0,0,1,0,1,0,2025,8,23


In [66]:
df_booking.shape



(100000, 66)

In [44]:

X = df_booking.drop(['booking_status'],axis = 1)
Y = df_booking['booking_status']

from sklearn.model_selection import train_test_split


x_train,x_test , y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state = 42,stratify=Y)


from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=2000,
    class_weight='balanced',
    random_state=42)

model.fit(x_train,y_train)

train_pred = model.predict(x_train)

test_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score,precision_score,recall_score, f1_score

print(f"Accuracy Score : {accuracy_score(y_train,train_pred)}")
print(f"precision_score Score : {precision_score(y_train,train_pred,average='micro')}")
print(f"recall_score Score : {recall_score(y_train,train_pred,average='micro')}")
print(f"f1_score Score : {f1_score(y_train,train_pred,average='micro')}")

print("\n")

print(f"Accuracy Score : {accuracy_score(y_test,test_pred)}")
print(f"precision_score Score : {precision_score(y_test,test_pred,average='micro')}")
print(f"recall_score Score : {recall_score(y_test,test_pred,average='micro')}")
print(f"f1_score Score : {f1_score(y_test,test_pred,average='micro')}")

c:\Users\KITTU-PALKIN\OneDrive\Documents\Rupahli\GUVI\Projects\Rapido\.rapido\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 2000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=2000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy Score : 0.6939625
precision_score Score : 0.6939625
recall_score Score : 0.6939625
f1_score Score : 0.6939625


Accuracy Score : 0.69155
precision_score Score : 0.69155
recall_score Score : 0.69155
f1_score Score : 0.69155


In [45]:
X = df_booking.drop(['booking_status'],axis = 1)
Y = df_booking['booking_status']

from sklearn.model_selection import train_test_split


x_train,x_test , y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state = 42,stratify=Y)

from sklearn.tree import DecisionTreeClassifier

dt_model= DecisionTreeClassifier(class_weight='balanced',random_state=42)
parameter = {
    "criterion":["gini", "entropy" , "log_loss"],
    "max_depth":[5,6,7,8],
    "min_samples_split":[25,30,35]

}
from sklearn.model_selection import GridSearchCV

model = GridSearchCV(estimator=dt_model,param_grid=parameter,scoring="accuracy")

model.fit(x_train,y_train)

print(f"Best Parameter : {model.best_params_}")
print(f"Best Score : {model.best_score_}")
print(f"Best estimator : {model.best_estimator_}")

Best Parameter : {'criterion': 'gini', 'max_depth': 7, 'min_samples_split': 25}
Best Score : 0.632625
Best estimator : DecisionTreeClassifier(class_weight='balanced', max_depth=7,
                       min_samples_split=25, random_state=42)


In [46]:
X = df_booking.drop(['booking_status'],axis = 1)
Y = df_booking['booking_status']

from sklearn.model_selection import train_test_split


x_train,x_test , y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state = 42,stratify=Y)


from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(class_weight='balanced',random_state=42,criterion='entropy', max_depth=7, min_samples_split=25)

model.fit(x_train,y_train)

train_pred = model.predict(x_train)

test_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score,precision_score,recall_score, f1_score

print(f"Accuracy Score : {accuracy_score(y_train,train_pred)}")
print(f"precision_score Score : {precision_score(y_train,train_pred,average='micro')}")
print(f"recall_score Score : {recall_score(y_train,train_pred,average='micro')}")
print(f"f1_score Score : {f1_score(y_train,train_pred,average='micro')}")

print("\n")

print(f"Accuracy Score : {accuracy_score(y_test,test_pred)}")
print(f"precision_score Score : {precision_score(y_test,test_pred,average='micro')}")
print(f"recall_score Score : {recall_score(y_test,test_pred,average='micro')}")
print(f"f1_score Score : {f1_score(y_test,test_pred,average='micro')}")

Accuracy Score : 0.60595
precision_score Score : 0.60595
recall_score Score : 0.60595
f1_score Score : 0.60595


Accuracy Score : 0.5973
precision_score Score : 0.5973
recall_score Score : 0.5973
f1_score Score : 0.5973


In [47]:
X = df_booking.drop(['booking_status'],axis = 1)
Y = df_booking['booking_status']

from sklearn.model_selection import train_test_split


x_train,x_test , y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state = 42,stratify=Y)


from sklearn.ensemble import AdaBoostClassifier,RandomForestClassifier

model = AdaBoostClassifier(random_state=42)

model.fit(x_train,y_train)

train_pred = model.predict(x_train)

test_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score,precision_score,recall_score, f1_score

print(f"Accuracy Score : {accuracy_score(y_train,train_pred)}")
print(f"precision_score Score : {precision_score(y_train,train_pred,average='micro')}")
print(f"recall_score Score : {recall_score(y_train,train_pred,average='micro')}")
print(f"f1_score Score : {f1_score(y_train,train_pred,average='micro')}")

print("\n")

print(f"Accuracy Score : {accuracy_score(y_test,test_pred)}")
print(f"precision_score Score : {precision_score(y_test,test_pred,average='micro')}")
print(f"recall_score Score : {recall_score(y_test,test_pred,average='micro')}")
print(f"f1_score Score : {f1_score(y_test,test_pred,average='micro')}")

Accuracy Score : 0.746475
precision_score Score : 0.746475
recall_score Score : 0.746475
f1_score Score : 0.746475


Accuracy Score : 0.74495
precision_score Score : 0.74495
recall_score Score : 0.74495
f1_score Score : 0.74495


In [54]:
df_booking.head()

'''df_booking.drop(
    ["completed_rides_x", "cancelled_rides_x", "completed_rides_y", "cancelled_rides_y", "incomplete_rides_y", "cancellation_rate"],
    axis=1,
    errors="ignore",
    inplace=True
)'''

'df_booking.drop(\n    ["completed_rides_x", "cancelled_rides_x", "completed_rides_y", "cancelled_rides_y", "incomplete_rides_y", "cancellation_rate"],\n    axis=1,\n    errors="ignore",\n    inplace=True\n)'

In [55]:
df_booking.head()

,is_weekend,hour_of_day,ride_distance_km,estimated_ride_time_min,traffic_level,weather_condition,base_fare,surge_multiplier,booking_value,booking_status,Fare_per_KM,Fare_per_Min,Long_Distance_Flag,total_requests,avg_wait_time_min,avg_surge_multiplier,day_of_week_Friday,day_of_week_Monday,day_of_week_Saturday,day_of_week_Sunday,day_of_week_Thursday,day_of_week_Tuesday,day_of_week_Wednesday,city_Bangalore,city_Chennai,city_Delhi,city_Hyderabad,city_Mumbai,vehicle_type_Auto_x,vehicle_type_Bike_x,vehicle_type_Cab_x,demand_level_Low,demand_level_Medium,peak_time_flag,driver_experience_years,total_assigned_rides,accepted_rides,incomplete_rides_x,delay_count,acceptance_rate,delay_rate,avg_driver_rating,avg_pickup_delay_min,driver_delay_flag,vehicle_type_Auto_y,vehicle_type_Bike_y,vehicle_type_Cab_y,customer_signup_days_ago,total_bookings,avg_customer_rating,customer_cancel_flag,preferred_vehicle_type_Auto,preferred_vehicle_type_Bike,preferred_vehicle_type_Cab,customer_gender_Female,customer_gender_Male,customer_gender_Non-Binary,booking_year,booking_month,booking_day
0,0,0,7.01,46.30,2.0,2.0,76.12,2.0,148.22,Cancelled,21.144080,3.201296,0,4,51.002500,1.525000,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,0,0,10,18,16,2,1,0.89,0.06,4.9,2.9,0,0,0,1,548,16,4.3,0,0,1,0,0,1,0,2025,12,11
1,0,6,9.67,43.54,1.0,2.0,254.15,1.8,465.85,Completed,48.174767,10.699357,0,4,47.202500,1.575000,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,5,18,14,2,1,0.78,0.06,4.6,3.9,0,1,0,0,848,10,4.7,0,0,0,1,1,0,0,2025,7,7
2,1,8,16.18,48.55,0.0,2.0,234.20,1.9,457.03,Cancelled,28.246601,9.413594,0,7,68.342857,1.685714,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,1,14,27,22,4,4,0.81,0.15,4.4,5.2,1,0,0,1,161,6,3.7,1,0,0,1,1,0,0,2025,8,23
3,1,10,1.02,4.61,1.0,1.0,28.20,1.8,51.03,Completed,50.029412,11.069414,0,3,27.963333,1.566667,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,1,0,1,14,25,17,3,2,0.68,0.08,4.2,3.2,0,0,0,1,322,11,3.7,0,0,0,1,1,0,0,2025,4,12
4,1,0,12.35,55.56,1.0,0.0,118.77,1.2,144.73,Completed,11.719028,2.604932,0,8,91.583750,1.400000,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,4,15,12,1,1,0.80,0.07,4.5,4.0,0,1,0,0,855,13,4.4,0,0,0,1,0,1,0,2025,8,23


In [16]:
df_booking.drop(
    ["booking_year", "Long_Distance_Flag", "booking_day", "is_weekend", "day_of_week_Monday", 'day_of_week_Tuesday',
    'day_of_week_Wednesday',
    'day_of_week_Thursday',
    'day_of_week_Friday',
    'day_of_week_Saturday',
    'day_of_week_Sunday'],
    axis=1,
    errors="ignore",
    inplace=True
)

In [67]:
X = df_booking.drop(['booking_status'],axis = 1)
Y = df_booking['booking_status']

from sklearn.model_selection import train_test_split


x_train,x_test , y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state = 42,stratify=Y)


from sklearn.ensemble import AdaBoostClassifier,RandomForestClassifier

model = RandomForestClassifier(n_estimators=300,
    max_depth=12,
    min_samples_leaf=5,
    class_weight='balanced_subsample',
    random_state=42,
    n_jobs=-1)

model.fit(x_train,y_train)

train_pred = model.predict(x_train)

test_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score,precision_score,recall_score, f1_score

print(f"Train Accuracy Score : {accuracy_score(y_train,train_pred)}")
print(f"Train precision_score Score : {precision_score(y_train,train_pred,average='micro')}")
print(f"Train recall_score Score : {recall_score(y_train,train_pred,average='micro')}")
print(f"Train f1_score Score : {f1_score(y_train,train_pred,average='micro')}")

print("\n")

print(f"Test Accuracy Score : {accuracy_score(y_test,test_pred)}")
print(f"Test precision_score Score : {precision_score(y_test,test_pred,average='micro')}")
print(f"Test recall_score Score : {recall_score(y_test,test_pred,average='micro')}")
print(f"Test f1_score Score : {f1_score(y_test,test_pred,average='micro')}")

from sklearn.metrics import classification_report, confusion_matrix, f1_score

print("Test macro-F1:", f1_score(y_test, test_pred, average="macro"))

print(classification_report(
    y_test,
    test_pred,
    labels=["Completed", "Cancelled", "Incomplete"],
    zero_division=0
))

print(confusion_matrix(
    y_test,
    test_pred,
    labels=["Completed", "Cancelled", "Incomplete"]
))

Train Accuracy Score : 0.775775
Train precision_score Score : 0.775775
Train recall_score Score : 0.775775
Train f1_score Score : 0.775775


Test Accuracy Score : 0.70865
Test precision_score Score : 0.70865
Test recall_score Score : 0.70865
Test f1_score Score : 0.70865
Test macro-F1: 0.6254391709329485
              precision    recall  f1-score   support

   Completed       0.89      0.71      0.79     13669
   Cancelled       0.57      0.74      0.64      4657
  Incomplete       0.34      0.64      0.45      1674

    accuracy                           0.71     20000
   macro avg       0.60      0.69      0.63     20000
weighted avg       0.77      0.71      0.73     20000

[[9677 2433 1559]
 [ 737 3424  496]
 [ 407  195 1072]]


In [17]:
X = df_booking.drop(['booking_status'],axis = 1)
Y = df_booking['booking_status']

from sklearn.model_selection import train_test_split


x_train,x_test , y_train,y_test = train_test_split(X,Y,test_size = 0.2,random_state = 42,stratify=Y)


from sklearn.svm import LinearSVC

model = LinearSVC(dual=False, max_iter=2000, random_state=42)

model.fit(x_train,y_train)

train_pred = model.predict(x_train)

test_pred = model.predict(x_test)

from sklearn.metrics import accuracy_score,precision_score,recall_score, f1_score

print(f"Accuracy Score : {accuracy_score(y_train,train_pred)}")
print(f"precision_score Score : {precision_score(y_train,train_pred,average='micro')}")
print(f"recall_score Score : {recall_score(y_train,train_pred,average='micro')}")
print(f"f1_score Score : {f1_score(y_train,train_pred,average='macro')}")

print("\n")

print(f"Test Accuracy Score : {accuracy_score(y_test,test_pred)}")
print(f"Test precision_score Score : {precision_score(y_test,test_pred,average='micro')}")
print(f"Test recall_score Score : {recall_score(y_test,test_pred,average='micro')}")
print(f"Test f1_score Score : {f1_score(y_test,test_pred,average='macro')}")

Accuracy Score : 0.72405
precision_score Score : 0.72405
recall_score Score : 0.72405
f1_score Score : 0.47095860244121424


Accuracy Score : 0.72425
precision_score Score : 0.72425
recall_score Score : 0.72425
f1_score Score : 0.4724170904654797


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import f1_score, classification_report, confusion_matrix

X = df_booking.drop(['booking_status'], axis=1)
Y = df_booking['booking_status']

x_train_tuned, x_test_tuned, y_train_tuned, y_test_tuned = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42,
    stratify=Y
)

custom_weights = {
    'Completed': 1.0,
    'Cancelled': 1.2,
    'Incomplete': 1.8
}

rf = RandomForestClassifier(
    random_state=42,
    n_jobs=-1
)

parameter_grid = {
    'n_estimators': [200],
    'max_depth': [10, 14],
    'min_samples_leaf': [5, 10],
    'class_weight': ['balanced_subsample', custom_weights]
}

grid_search = GridSearchCV(
    estimator=rf,
    param_grid=parameter_grid,
    scoring='f1_macro',
    cv=3,
    n_jobs=-1,
    verbose=1
)

grid_search.fit(x_train_tuned, y_train_tuned)

best_rf = grid_search.best_estimator_
tuned_pred = best_rf.predict(x_test_tuned)

print('Best parameters:', grid_search.best_params_)
print('Best cross-validation macro-F1:', grid_search.best_score_)
print('Test macro-F1:', f1_score(y_test_tuned, tuned_pred, average='macro'))
print()
print(classification_report(
    y_test_tuned,
    tuned_pred,
    labels=['Completed', 'Cancelled', 'Incomplete'],
    zero_division=0
))
print('Confusion matrix:')
print(confusion_matrix(
    y_test_tuned,
    tuned_pred,
    labels=['Completed', 'Cancelled', 'Incomplete']
))

coefficients_df = pd.DataFrame({
    'Feature Name': x_train_tuned.columns,
    'Feature Importance': best_rf.feature_importances_
})

coefficients_df = coefficients_df.sort_values(
    by='Feature Importance',
    ascending=False
)

print('--- Random Forest Feature Importance ---')
print(coefficients_df.to_string(index=False))

Fitting 3 folds for each of 8 candidates, totalling 24 fits
Best parameters: {'class_weight': 'balanced_subsample', 'max_depth': 14, 'min_samples_leaf': 5, 'n_estimators': 200}
Best cross-validation macro-F1: 0.6391917715059239
Test macro-F1: 0.6401566110675686

              precision    recall  f1-score   support

   Completed       0.88      0.75      0.81     13669
   Cancelled       0.58      0.73      0.64      4657
  Incomplete       0.39      0.57      0.46      1674

    accuracy                           0.73     20000
   macro avg       0.62      0.68      0.64     20000
weighted avg       0.77      0.73      0.74     20000

Confusion matrix:
[[10316  2228  1125]
 [  890  3383   384]
 [  492   225   957]]
--- Random Forest Feature Importance ---
               Feature Name  Feature Importance
         incomplete_rides_y            0.157098
          cancelled_rides_x            0.106083
         incomplete_rides_x            0.063034
          cancellation_rate            0.

: 

In [14]:
from sklearn.base import clone
from sklearn.metrics import f1_score

features_to_remove = [
    'booking_year',
    'Long_Distance_Flag',
    'booking_day',
    'is_weekend'
]

X_reduced = X.drop(columns=features_to_remove, errors='ignore')

x_train_reduced, x_test_reduced, y_train_reduced, y_test_reduced = train_test_split(
    X_reduced,
    Y,
    test_size=0.2,
    random_state=42,
    stratify=Y
)

reduced_model = clone(best_rf)
reduced_model.fit(x_train_reduced, y_train_reduced)

reduced_pred = reduced_model.predict(x_test_reduced)

print(
    'Reduced test macro-F1:',
    f1_score(y_test_reduced, reduced_pred, average='macro')
)

Reduced test macro-F1: 0.6354555443321712


In [15]:
day_features = [
    'day_of_week_Monday',
    'day_of_week_Tuesday',
    'day_of_week_Wednesday',
    'day_of_week_Thursday',
    'day_of_week_Friday',
    'day_of_week_Saturday',
    'day_of_week_Sunday',
    'is_weekend'
]

X_without_day = X.drop(columns=day_features, errors='ignore')

x_train_day, x_test_day, y_train_day, y_test_day = train_test_split(
    X_without_day,
    Y,
    test_size=0.2,
    random_state=42,
    stratify=Y
)

day_model = clone(best_rf)
day_model.fit(x_train_day, y_train_day)

day_pred = day_model.predict(x_test_day)

print(
    'Without day features macro-F1:',
    f1_score(y_test_day, day_pred, average='macro')
)

Without day features macro-F1: 0.6389453435243438
